services:
  server:
    build:
      context: .
      dockerfile: Chat/Server/Dockerfile
    restart: unless-stopped
    command:
      - "11000"
    networks:
      - appnet
        
  client:
    build:
      context: .
      dockerfile: Chat/Client/Dockerfile
    restart: unless-stopped
    command:
      - "server"
      - "11000"
    depends_on:
      - server
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    driver: bridge     