services:
  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    command: [ "nginx", '-g', 'daemon off;' ]
    ports:
      - '8080:8080'
    depends_on:
      - valuator 
    networks:
      - internet
      - appnet  
  
  valuator:
    image: valuator
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    restart: unless-stopped  
    environment:
      - "URLS=http://*:5141/"
      - "ASPNETCORE_URLS=http://*:5141/"
      - "REDIS_ADDRESS=redis-db"
      - "REDIS_PORT=6379"
    depends_on: 
      - redis-db
    networks: 
      - appnet
    deploy:
      mode: replicated
      replicas: 3
  
  redis-db:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-cache:/data
    networks:
      - appnet 
 
networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge        
        
volumes:
  redis-cache:
    driver: local