services:
  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    command: [ "nginx", '-g', 'daemon off;' ]
    ports:
      - '8080:8080'
    depends_on:
      - valuator 
    networks:
      - internet
      - appnet  
  
  valuator:
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    restart: unless-stopped  
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "URLS=http://*:5141/"
      - "ASPNETCORE_URLS=http://*:5141/"
      - "REDIS_ADDRESS=redis-db"
      - "REDIS_PORT=6379"
      - "NATS_URL=nats://nats:4222"
    depends_on: 
      - redis-db
      - nats
      - similarity-calculator
      - rank-calculator
    networks: 
      - appnet
    deploy:
      mode: replicated
      replicas: 3
    
  rank-calculator:
    build:
      context: .
      dockerfile: RankCalculator/Dockerfile
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "REDIS_ADDRESS=redis-db"
      - "REDIS_PORT=6379"
      - "NATS_URL=nats://nats:4222"
    depends_on:
      - redis-db
      - nats
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 3 

  similarity-calculator:
    build:
      context: .
      dockerfile: SimilarityCalculator/Dockerfile
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "REDIS_ADDRESS=redis-db"
      - "REDIS_PORT=6379"
      - "NATS_URL=nats://nats:4222"
    depends_on:
      - redis-db
      - nats
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 3
  
  events-logger:
    build:
      context: .
      dockerfile: EventsLogger/Dockerfile
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "NATS_URL=nats://nats:4222"
    depends_on:
      - nats
      - similarity-calculator
      - rank-calculator
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 2
  
  redis-db:
    image: redis:6.2-alpine
    restart: always
#    ports:
#      - "6379:6379" #Debug
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-cache:/data
    networks:
      - appnet 

  nats:
    image: nats
    ports:
      - "8222:8222"
#      - "4222:4222" #Debug
    command: "--http_port 8222"
    networks:
      - appnet
 
networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge        
        
volumes:
  redis-cache:
    driver: local